//! eFMU container primitives for the generic packaging build step (contract
//! §6 relocation; formerly `rumoca-efmi::container`).
//!
//! Two product-specific-but-declared helpers the declarative build step
//! ([`crate::packaging`]) drives:
//!
//! - [`asset_bundle_files`] resolves a declared `[[assets]]` bundle name to the
//!   vendored eFMI Beta-1 XSD tree, embedded by `build.rs` from
//!   `assets/efmi-schemas/` and shipped byte-identically with its BSD-3-Clause
//!   `LICENSE` (GAL-023);
//! - [`write_efmu_zip`] zips a written eFMU directory into the `.efmu` archive
//!   form, `__content.xml` at the zip root, deterministically (fixed
//!   timestamp/permissions so repeated packaging is byte-reproducible).
//!
//! There is no XML here: manifest/`__content.xml` text is owned by the
//! minijinja templates (SPEC_0034 D3 amended). The former write-time re-parse
//! checksum cross-check (`verify_manifest_consistency`) is deleted — the build
//! step hashes the exact rendered bytes it writes, and the CI recompute
//! -from-disk test is the stronger black-box guarantee (contract §5/§7).

use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

/// One embedded vendored schema file; `relative_path` is `/`-separated and
/// relative to the emitted `schemas/` directory. The `SCHEMA_ASSETS` static is
/// generated by `build.rs` from `assets/efmi-schemas/`.
struct SchemaAsset {
    relative_path: &'static str,
    bytes: &'static [u8],
}

include!(concat!(env!("OUT_DIR"), "/schema_assets.rs"));

/// Name of the container content description reserved at the eFMU root by the
/// standard (eFMI ch. 2): `__content.xml`.
const CONTENT_XML_NAME: &str = "__content.xml";

/// Logical name of the vendored eFMI XSD bundle, matching the `[[assets]]`
/// `bundle` declaration in the `galec`/`galec-production` targets.
const EFMI_SCHEMA_BUNDLE: &str = "efmi-schemas";

/// Enumerate the embedded files of a named vendored asset bundle as
/// `(bundle-relative /-separated path, exact bytes)` pairs, for the generic
/// packaging build step to copy verbatim into a product (contract §4d).
/// `None` for an unknown bundle name so the caller can fail early. The only
/// bundle is [`EFMI_SCHEMA_BUNDLE`] — the vendored Beta-1 XSD tree plus its
/// BSD-3-Clause `LICENSE`, embedded by `build.rs` and shipped byte-identically
/// (GAL-023). The order is `build.rs`'s deterministic path-sorted order.
pub(crate) fn asset_bundle_files(bundle: &str) -> Option<Vec<(&'static str, &'static [u8])>> {
    match bundle {
        EFMI_SCHEMA_BUNDLE => Some(
            SCHEMA_ASSETS
                .iter()
                .map(|asset| (asset.relative_path, asset.bytes))
                .collect(),
        ),
        _ => None,
    }
}

/// Zip a written eFMU directory into its `.efmu` archive form (contract §4b):
/// `__content.xml` at the zip root (no wrapper directory), extension `.efmu`.
///
/// The archive is a pure function of the directory contents (fixed
/// timestamp/permissions), so repeated packaging is byte-reproducible. Written
/// to a staging path beside `zip_path` and renamed into place on success, so a
/// partial failure never leaves a corrupt `.efmu` (nor destroys a previous
/// valid archive).
///
/// # Errors
///
/// The path does not end in `.efmu`, the directory is not an eFMU root (no
/// `__content.xml`), a symlink/non-UTF-8 name is found inside the tree, or any
/// I/O / zip-write failure.
pub(crate) fn write_efmu_zip(efmu_root: &Path, zip_path: &Path) -> Result<()> {
    if zip_path.extension().and_then(|e| e.to_str()) != Some("efmu") {
        bail!(
            "eFMU zip archives must use the `.efmu` extension: `{}`",
            zip_path.display()
        );
    }
    if !efmu_root.join(CONTENT_XML_NAME).is_file() {
        bail!(
            "not an eFMU root: `{CONTENT_XML_NAME}` is missing under `{}`",
            efmu_root.display()
        );
    }
    let mut relative_paths = Vec::new();
    collect_files(efmu_root, efmu_root, &mut relative_paths)?;
    relative_paths.sort();
    write_zip_entries(efmu_root, zip_path, &relative_paths)
}

/// Recursively collect files under `dir` as `/`-separated zip entry names
/// relative to `root`. Symlinks are refused (an eFMU tree is plain files).
fn collect_files(root: &Path, dir: &Path, out: &mut Vec<String>) -> Result<()> {
    let entries =
        fs::read_dir(dir).with_context(|| format!("Read eFMU directory `{}`", dir.display()))?;
    for entry in entries {
        let entry =
            entry.with_context(|| format!("Read eFMU directory entry in `{}`", dir.display()))?;
        let path = entry.path();
        // `DirEntry::file_type` does not follow symlinks, unlike `Path::is_dir`.
        let file_type = entry
            .file_type()
            .with_context(|| format!("Stat `{}`", path.display()))?;
        if file_type.is_symlink() {
            bail!(
                "symlinks are not supported inside an eFMU tree: `{}`",
                path.display()
            );
        }
        if file_type.is_dir() {
            collect_files(root, &path, out)?;
            continue;
        }
        out.push(relative_entry_name(root, &path)?);
    }
    Ok(())
}

/// Render `path` relative to `root` as a `/`-separated UTF-8 zip entry name.
fn relative_entry_name(root: &Path, path: &Path) -> Result<String> {
    let mut segments = Vec::new();
    for component in path
        .strip_prefix(root)
        .expect("walked path is under the walk root")
        .components()
    {
        let Some(segment) = component.as_os_str().to_str() else {
            bail!(
                "file names inside an eFMU tree must be valid UTF-8: `{}`",
                path.display()
            );
        };
        segments.push(segment);
    }
    Ok(segments.join("/"))
}

/// Write the archive to a staging path beside `zip_path` and rename it into
/// place on success. `fs::File::create` truncates immediately, so writing
/// straight to the final path would leave a corrupt `.efmu` behind — and
/// destroy a previous run's valid archive — if a source read or entry write
/// fails partway; the staging file is removed on error instead.
fn write_zip_entries(efmu_root: &Path, zip_path: &Path, relative_paths: &[String]) -> Result<()> {
    let mut staging_name = zip_path
        .file_name()
        .expect("zip path ends in `.efmu`, so it has a file name")
        .to_os_string();
    staging_name.push(".part");
    let staging_path = zip_path.with_file_name(staging_name);
    write_zip_archive(efmu_root, zip_path, &staging_path, relative_paths).inspect_err(|_| {
        let _ = fs::remove_file(&staging_path);
    })?;
    // Renaming over an existing file replaces it on Unix but fails on Windows,
    // so a previous archive is removed first — only now that the staged
    // replacement is complete.
    if zip_path.exists() {
        fs::remove_file(zip_path)
            .with_context(|| format!("Remove previous archive `{}`", zip_path.display()))?;
    }
    fs::rename(&staging_path, zip_path)
        .with_context(|| format!("Rename `{}` into place", zip_path.display()))
}

/// Write every entry into the staged archive at `staging_path`.
fn write_zip_archive(
    efmu_root: &Path,
    zip_path: &Path,
    staging_path: &Path,
    relative_paths: &[String],
) -> Result<()> {
    let file = fs::File::create(staging_path)
        .with_context(|| format!("Create staged archive `{}`", staging_path.display()))?;
    let mut zip = zip::ZipWriter::new(file);
    // Fixed timestamp + permissions: the archive is a pure function of the
    // directory contents, so repeated packaging is byte-reproducible.
    let options = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated)
        .last_modified_time(zip::DateTime::default())
        .unix_permissions(0o644);
    for relative in relative_paths {
        let source: PathBuf = efmu_root.join(relative.replace('/', std::path::MAIN_SEPARATOR_STR));
        let bytes =
            fs::read(&source).with_context(|| format!("Read eFMU file `{}`", source.display()))?;
        zip.start_file(relative, options)
            .with_context(|| format!("Start zip entry `{relative}` in `{}`", zip_path.display()))?;
        zip.write_all(&bytes)
            .with_context(|| format!("Write zip entry `{relative}` in `{}`", zip_path.display()))?;
    }
    zip.finish()
        .with_context(|| format!("Finish archive `{}`", zip_path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    /// The embedded asset list must mirror `assets/efmi-schemas/` exactly
    /// (minus the repository-only `README.md`), byte for byte — catching both
    /// build-script drift and accidental asset edits (GAL-023).
    #[test]
    fn embedded_assets_match_vendored_tree() {
        let assets_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("assets")
            .join("efmi-schemas");

        let mut on_disk: BTreeMap<String, Vec<u8>> = BTreeMap::new();
        collect_disk_assets(&assets_dir, &assets_dir, &mut on_disk);
        // The top-level README.md is repository documentation, not part of the
        // distributed schema bundle (mirrors build.rs's EXCLUDED_ROOT_FILES).
        on_disk.remove("README.md");

        let embedded: BTreeMap<String, Vec<u8>> = SCHEMA_ASSETS
            .iter()
            .map(|asset| (asset.relative_path.to_owned(), asset.bytes.to_vec()))
            .collect();

        assert_eq!(
            embedded.keys().collect::<Vec<_>>(),
            on_disk.keys().collect::<Vec<_>>(),
            "embedded schema asset paths must match the vendored tree exactly"
        );
        for (path, bytes) in &on_disk {
            assert_eq!(
                embedded.get(path),
                Some(bytes),
                "embedded bytes for `{path}` must match the vendored file byte-for-byte"
            );
        }
        assert!(
            embedded.contains_key("LICENSE"),
            "the BSD-3-Clause LICENSE must travel with the vendored XSDs (GAL-023)"
        );
    }

    fn collect_disk_assets(root: &Path, dir: &Path, out: &mut BTreeMap<String, Vec<u8>>) {
        for entry in fs::read_dir(dir).expect("read vendored asset dir") {
            let entry = entry.expect("read vendored asset entry");
            let path = entry.path();
            if path.is_dir() {
                collect_disk_assets(root, &path, out);
                continue;
            }
            let relative = path
                .strip_prefix(root)
                .expect("asset path under root")
                .components()
                .map(|c| c.as_os_str().to_str().expect("asset paths are UTF-8"))
                .collect::<Vec<_>>()
                .join("/");
            out.insert(relative, fs::read(&path).expect("read vendored asset file"));
        }
    }
}
