# Pin nightly toolchain for WASM threading support
# See: https://github.com/RReverser/wasm-bindgen-rayon
[toolchain]
channel = "nightly-2026-02-27"
components = ["llvm-tools-preview", "rust-src"]
targets = ["wasm32-unknown-unknown"]
