use anyhow::{Context, Result};
use serde_json::Value;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_RESULTS_DIR: &str = "target/msl/results";
const DEFAULT_OUTPUT_FILE: &str = "msl_pr_comment.md";
const DEFAULT_BASELINE_FILE: &str =
    "crates/rumoca-test-msl/tests/msl_tests/msl_quality_baseline.json";
const COMMENT_MARKER: &str = "<!-- rumoca-msl-quality-summary -->";
const SIZE_BINS: &[(u64, Option<u64>)] = &[
    (1, Some(9)),
    (10, Some(24)),
    (25, Some(49)),
    (50, Some(99)),
    (100, Some(249)),
    (250, None),
];
const SLOWEST_MODEL_LIMIT: usize = 10;

#[derive(Debug, clap::Args, Clone)]
pub struct Args {
    /// MSL results directory containing markdown report artifacts
    #[arg(long, default_value = DEFAULT_RESULTS_DIR)]
    pub results_dir: PathBuf,
    /// Markdown file to write for CI PR publication
    #[arg(long)]
    pub out: Option<PathBuf>,
    /// Quality baseline used to render summary deltas
    #[arg(long, default_value = DEFAULT_BASELINE_FILE)]
    pub baseline: PathBuf,
}

pub fn run(args: Args) -> Result<()> {
    let out = args
        .out
        .clone()
        .unwrap_or_else(|| args.results_dir.join(DEFAULT_OUTPUT_FILE));
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    let body = render_pr_comment(&args.results_dir, Some(&args.baseline))?;
    fs::write(&out, body).with_context(|| format!("failed to write {}", out.display()))?;
    println!("MSL PR comment summary written to {}", out.display());
    Ok(())
}

fn render_pr_comment(results_dir: &Path, baseline_path: Option<&Path>) -> Result<String> {
    let mut body = String::new();
    body.push_str(COMMENT_MARKER);
    body.push_str("\n### MSL Quality Gate Summary\n\n");
    body.push_str("_Generated by `cargo xtask repo msl pr-comment` from CI result artifacts._\n\n");

    if let Some(summary) = render_quality_snapshot_summary(results_dir, baseline_path)? {
        body.push_str(&summary);
        body.push('\n');
    }

    append_report_section(
        &mut body,
        "Package Pass Rates",
        &results_dir.join("msl_package_pass_rates.md"),
    )?;
    append_report_section(
        &mut body,
        "MLS Contract Coverage",
        &results_dir.join("mls_contract_coverage.md"),
    )?;
    append_report_section(
        &mut body,
        "Trace Accuracy vs OMC",
        &results_dir.join("msl_package_trace_accuracy.md"),
    )?;
    body.push_str("#### Speed vs OMC\n\n");
    body.push_str(&render_speed_section(results_dir)?);
    body.push_str("\n\n");
    append_optional_link_note(&mut body, results_dir);

    Ok(body)
}

fn render_quality_snapshot_summary(
    results_dir: &Path,
    baseline_path: Option<&Path>,
) -> Result<Option<String>> {
    let quality_path = results_dir.join("msl_quality_current.json");
    if !quality_path.is_file() {
        return Ok(None);
    }
    let text = fs::read_to_string(&quality_path)
        .with_context(|| format!("failed to read {}", quality_path.display()))?;
    let json: Value = serde_json::from_str(&text)
        .with_context(|| format!("failed to parse {}", quality_path.display()))?;
    let baseline = load_quality_baseline(baseline_path)?;

    let run_scope = json_str(&json, "run_scope").unwrap_or("unknown");
    let msl_version = json_str(&json, "msl_version").unwrap_or("unknown");
    let omc_version = json_str(&json, "omc_version").unwrap_or("unknown");
    let compile = quality_metric_cell(
        &json,
        baseline.as_ref(),
        "compiled_models",
        "balance_denominator",
    );
    let balance = quality_metric_cell(
        &json,
        baseline.as_ref(),
        "balanced_models",
        "balance_denominator",
    );
    let initial_balance = quality_metric_cell(
        &json,
        baseline.as_ref(),
        "initial_balanced_models",
        "balance_denominator",
    );
    let simulation = quality_metric_cell(&json, baseline.as_ref(), "sim_ok", "sim_target_models");
    let mut delta_note = String::new();
    if let Some(baseline) = baseline.as_ref() {
        delta_note.push_str(
            "\n_Deltas compare numerator/denominator against the resolved MSL quality baseline._\n",
        );
        delta_note.push_str(&baseline_identity_note(baseline));
        if let Some(trace_note) = trace_baseline_delta_note(&json, baseline) {
            delta_note.push_str(&trace_note);
        }
    }

    let ci_gate_metrics = render_ci_gate_metrics_table(&json, baseline.as_ref());

    Ok(Some(format!(
        "| Scope | MSL | OMC | Compile | Balance | Initial Balance | Simulation |\n\
         |---|---|---|---:|---:|---:|---:|\n\
         | `{run_scope}` | `{msl_version}` | `{omc_version}` | {compile} | {balance} | {initial_balance} | {simulation} |\n\
         {delta_note}\n\
         {ci_gate_metrics}"
    )))
}

fn load_quality_baseline(path: Option<&Path>) -> Result<Option<Value>> {
    let Some(path) = path else {
        return Ok(None);
    };
    if !path.is_file() {
        return Ok(None);
    }
    let text =
        fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))?;
    serde_json::from_str(&text)
        .map(Some)
        .with_context(|| format!("failed to parse {}", path.display()))
}

fn quality_metric_cell(
    json: &Value,
    baseline: Option<&Value>,
    num_key: &str,
    den_key: &str,
) -> String {
    let numerator = json_u64(json, num_key).unwrap_or(0);
    let denominator = json_u64(json, den_key).unwrap_or(0);
    let Some(baseline) = baseline else {
        return format!("{numerator}/{denominator}");
    };
    let base_numerator = json_u64(baseline, num_key).unwrap_or(0);
    let base_denominator = json_u64(baseline, den_key).unwrap_or(0);
    format!(
        "{numerator}/{denominator} (Δ{}/{})",
        signed_delta(numerator, base_numerator),
        signed_delta(denominator, base_denominator)
    )
}

fn render_ci_gate_metrics_table(json: &Value, baseline: Option<&Value>) -> String {
    let mut out = String::from(
        "#### CI Gate Snapshot\n\n\
         _These are the baseline-relative MSL stats checked by CI; IC progress is contextual unless simulation successes regress, and speed metrics are informational only._\n\n\
         | Gate area | Current (Δ vs baseline) |\n\
         |---|---:|\n",
    );
    out.push_str(&compact_structural_gate_row(json, baseline));
    out.push_str(&compact_balance_gate_row(json, baseline));
    out.push_str(&compact_runtime_gate_row(json, baseline));
    if let Some(row) = compact_trace_gate_row(json, baseline) {
        out.push_str(&row);
    }
    out.push_str("\n<details>\n<summary><strong>CI gate details</strong></summary>\n\n");
    out.push_str(&render_ci_gate_detail_table(json, baseline));
    out.push_str("\n</details>\n");
    out
}

fn compact_structural_gate_row(json: &Value, baseline: Option<&Value>) -> String {
    let keys = [
        ("parse", "parse_models"),
        ("flat", "flatten_models"),
        ("DAE", "compiled_models"),
        ("solve", "solve_models"),
    ];
    compact_gate_row("Structural floors", json, baseline, &keys, None)
}

fn compact_balance_gate_row(json: &Value, baseline: Option<&Value>) -> String {
    let keys = [
        ("balance", "balanced_models"),
        ("init", "initial_balanced_models"),
    ];
    compact_gate_row(
        "Balance floors",
        json,
        baseline,
        &keys,
        Some("balance_denominator"),
    )
}

fn compact_runtime_gate_row(json: &Value, baseline: Option<&Value>) -> String {
    let keys = [("IC progress", "ic_ok"), ("sim", "sim_ok")];
    compact_gate_row(
        "Runtime gate",
        json,
        baseline,
        &keys,
        Some("sim_target_models"),
    )
}

fn compact_gate_row(
    label: &str,
    json: &Value,
    baseline: Option<&Value>,
    keys: &[(&str, &str)],
    denominator_key: Option<&str>,
) -> String {
    let current = compact_gate_values(json, keys, denominator_key);
    let Some(baseline) = baseline else {
        return format!("| {label} | {current} |\n");
    };
    let values = keys
        .iter()
        .map(|(name, key)| {
            let current = json_u64(json, key).unwrap_or(0);
            let base = json_u64(baseline, key).unwrap_or(0);
            let denominator = denominator_key.and_then(|key| json_u64(json, key));
            format!(
                "{name} {} ({})",
                gate_count_cell(current, denominator),
                signed_delta(current, base)
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    format!("| {label} | {values} |\n")
}

fn compact_gate_values(
    json: &Value,
    keys: &[(&str, &str)],
    denominator_key: Option<&str>,
) -> String {
    let denominator = denominator_key.and_then(|key| json_u64(json, key));
    keys.iter()
        .map(|(name, key)| {
            let count = json_u64(json, key).unwrap_or(0);
            format!("{name} {}", gate_count_cell(count, denominator))
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn compact_trace_gate_row(json: &Value, baseline: Option<&Value>) -> Option<String> {
    let current_trace = json.get("trace_accuracy_stats")?;
    let current_acceptable =
        json_u64(current_trace, "agreement_high")? + json_u64(current_trace, "agreement_minor")?;
    let current_no_severe = trace_no_severe_count(current_trace)?;
    let current_compared = json_u64(current_trace, "models_compared")?;
    let current_target = json_u64(json, "sim_target_models");
    let current = format!(
        "acceptable {}, no-severe {}, compared {}",
        gate_count_cell(current_acceptable, current_target),
        gate_count_cell(current_no_severe, current_target),
        current_compared,
    );
    let Some(baseline) = baseline else {
        return Some(format!("| Trace floors | {current} |\n"));
    };
    let base_trace = baseline.get("trace_accuracy_stats")?;
    let base_acceptable =
        json_u64(base_trace, "agreement_high")? + json_u64(base_trace, "agreement_minor")?;
    let base_no_severe = trace_no_severe_count(base_trace)?;
    let base_compared = json_u64(base_trace, "models_compared")?;
    let values = format!(
        "acceptable {} ({}), no-severe {} ({}), compared {} ({})",
        gate_count_cell(current_acceptable, current_target),
        signed_delta(current_acceptable, base_acceptable),
        gate_count_cell(current_no_severe, current_target),
        signed_delta(current_no_severe, base_no_severe),
        current_compared,
        signed_delta(current_compared, base_compared),
    );
    Some(format!("| Trace floors | {values} |\n"))
}

fn render_ci_gate_detail_table(json: &Value, baseline: Option<&Value>) -> String {
    let mut out = String::from(
        "| CI gate metric | Current | Baseline | Δ |\n\
         |---|---:|---:|---:|\n",
    );
    push_gate_count_row(
        &mut out,
        "Parse floor",
        json,
        baseline,
        "parse_models",
        Some("simulatable_attempted"),
    );
    push_gate_count_row(
        &mut out,
        "Flatten floor",
        json,
        baseline,
        "flatten_models",
        Some("simulatable_attempted"),
    );
    push_gate_count_row(
        &mut out,
        "DAE/compile floor",
        json,
        baseline,
        "compiled_models",
        Some("simulatable_attempted"),
    );
    push_gate_count_row(
        &mut out,
        "Solve-IR floor",
        json,
        baseline,
        "solve_models",
        Some("simulatable_attempted"),
    );
    push_gate_count_row(
        &mut out,
        "Balance floor",
        json,
        baseline,
        "balanced_models",
        Some("balance_denominator"),
    );
    push_gate_count_row(
        &mut out,
        "Initial balance floor",
        json,
        baseline,
        "initial_balanced_models",
        Some("balance_denominator"),
    );
    push_gate_count_row(
        &mut out,
        "IC progress",
        json,
        baseline,
        "ic_ok",
        Some("sim_target_models"),
    );
    push_gate_count_row(
        &mut out,
        "Simulation floor",
        json,
        baseline,
        "sim_ok",
        Some("sim_target_models"),
    );
    push_gate_count_row(
        &mut out,
        "Partial models ceiling",
        json,
        baseline,
        "partial_models",
        None,
    );
    push_gate_count_row(
        &mut out,
        "Unbalanced models ceiling",
        json,
        baseline,
        "unbalanced_models",
        None,
    );
    if let Some(row) = trace_acceptable_gate_row(json, baseline) {
        out.push_str(&row);
    }
    if let Some(row) = trace_no_severe_gate_row(json, baseline) {
        out.push_str(&row);
    }
    if let Some(row) = trace_compared_gate_row(json, baseline) {
        out.push_str(&row);
    }
    out
}

fn push_gate_count_row(
    out: &mut String,
    label: &str,
    json: &Value,
    baseline: Option<&Value>,
    count_key: &str,
    denominator_key: Option<&str>,
) {
    let current = json_u64(json, count_key).unwrap_or(0);
    let current_denominator = denominator_key.and_then(|key| json_u64(json, key));
    let Some(baseline) = baseline else {
        out.push_str(&format!(
            "| {label} | {} | n/a | n/a |\n",
            gate_count_cell(current, current_denominator)
        ));
        return;
    };
    let base = json_u64(baseline, count_key).unwrap_or(0);
    let base_denominator = denominator_key.and_then(|key| json_u64(baseline, key));
    out.push_str(&format!(
        "| {label} | {} | {} | {} |\n",
        gate_count_cell(current, current_denominator),
        gate_count_cell(base, base_denominator),
        signed_delta(current, base)
    ));
}

fn gate_count_cell(count: u64, denominator: Option<u64>) -> String {
    denominator.map_or_else(
        || count.to_string(),
        |denominator| format!("{count}/{denominator}"),
    )
}

fn trace_acceptable_gate_row(json: &Value, baseline: Option<&Value>) -> Option<String> {
    let current_trace = json.get("trace_accuracy_stats")?;
    let current =
        json_u64(current_trace, "agreement_high")? + json_u64(current_trace, "agreement_minor")?;
    let current_denominator = json_u64(json, "sim_target_models");
    let Some(baseline) = baseline else {
        return Some(format!(
            "| Trace acceptable floor | {} | n/a | n/a |\n",
            gate_count_cell(current, current_denominator)
        ));
    };
    let base_trace = baseline.get("trace_accuracy_stats")?;
    let base = json_u64(base_trace, "agreement_high")? + json_u64(base_trace, "agreement_minor")?;
    Some(format!(
        "| Trace acceptable floor | {} | {} | {} |\n",
        gate_count_cell(current, current_denominator),
        gate_count_cell(base, json_u64(baseline, "sim_target_models")),
        signed_delta(current, base)
    ))
}

fn trace_no_severe_gate_row(json: &Value, baseline: Option<&Value>) -> Option<String> {
    let current_trace = json.get("trace_accuracy_stats")?;
    let current = trace_no_severe_count(current_trace)?;
    let current_denominator = json_u64(json, "sim_target_models");
    let Some(baseline) = baseline else {
        return Some(format!(
            "| Trace no-severe floor | {} | n/a | n/a |\n",
            gate_count_cell(current, current_denominator)
        ));
    };
    let base = trace_no_severe_count(baseline.get("trace_accuracy_stats")?)?;
    Some(format!(
        "| Trace no-severe floor | {} | {} | {} |\n",
        gate_count_cell(current, current_denominator),
        gate_count_cell(base, json_u64(baseline, "sim_target_models")),
        signed_delta(current, base)
    ))
}

fn trace_no_severe_count(trace: &Value) -> Option<u64> {
    let compared = json_u64(trace, "models_compared")?;
    let severe = json_u64(trace, "models_with_severe_channel")?;
    Some(compared.saturating_sub(severe))
}

fn trace_compared_gate_row(json: &Value, baseline: Option<&Value>) -> Option<String> {
    let current = json_u64(json.get("trace_accuracy_stats")?, "models_compared")?;
    let Some(baseline) = baseline else {
        return Some(format!(
            "| Trace compared floor (drop ≤2) | {current} | n/a | n/a |\n"
        ));
    };
    let base = json_u64(baseline.get("trace_accuracy_stats")?, "models_compared")?;
    Some(format!(
        "| Trace compared floor (drop ≤2) | {current} | {base} | {} |\n",
        signed_delta(current, base)
    ))
}

fn trace_baseline_delta_note(json: &Value, baseline: &Value) -> Option<String> {
    let current = json.get("trace_accuracy_stats")?;
    let base = baseline.get("trace_accuracy_stats")?;
    let current_agree =
        json_u64(current, "agreement_high")? + json_u64(current, "agreement_minor")?;
    let base_agree = json_u64(base, "agreement_high")? + json_u64(base, "agreement_minor")?;
    let current_deviation = json_u64(current, "agreement_deviation")?;
    let base_deviation = json_u64(base, "agreement_deviation")?;
    Some(format!(
        "_Trace agreement vs baseline: high+near Δ{}, deviation Δ{}._\n",
        signed_delta(current_agree, base_agree),
        signed_delta(current_deviation, base_deviation),
    ))
}

fn baseline_identity_note(baseline: &Value) -> String {
    let version = json_u64(baseline, "quality_gate_version")
        .map(|value| value.to_string())
        .unwrap_or_else(|| "unknown".to_string());
    let commit = json_str(baseline, "git_commit")
        .map(short_commit)
        .unwrap_or("unknown");
    let msl = json_str(baseline, "msl_version").unwrap_or("unknown");
    let omc = json_str(baseline, "omc_version").unwrap_or("unknown");
    format!("_Baseline: quality gate v{version}, commit `{commit}`, MSL `{msl}`, OMC `{omc}`._\n")
}

fn short_commit(commit: &str) -> &str {
    commit.get(..7).unwrap_or(commit)
}

fn signed_delta(current: u64, baseline: u64) -> String {
    let delta = current as i128 - baseline as i128;
    if delta > 0 {
        format!("+{delta}")
    } else {
        delta.to_string()
    }
}

#[derive(Clone)]
struct SpeedRecord {
    model_name: String,
    scalar_equations: u64,
    rumoca_frontend_compile: f64,
    rumoca_sim_build: f64,
    rumoca_sim_run: f64,
    omc_compile: f64,
    omc_sim: f64,
    omc_total: f64,
}

impl SpeedRecord {
    fn rumoca_compile(&self) -> f64 {
        self.rumoca_frontend_compile + self.rumoca_sim_build
    }

    fn rumoca_total(&self) -> f64 {
        self.rumoca_compile() + self.rumoca_sim_run
    }
}

#[derive(Clone, Copy)]
enum SpeedView {
    Total,
    Compilation,
    Simulation,
}

impl SpeedView {
    fn title(self) -> &'static str {
        match self {
            Self::Total => "Table 1 — Total (model → simulated results)",
            Self::Compilation => "Table 2 — Compilation (build-to-runnable)",
            Self::Simulation => "Table 3 — Simulation (integration only)",
        }
    }

    fn label(self) -> &'static str {
        match self {
            Self::Total => "Total",
            Self::Compilation => "Compilation",
            Self::Simulation => "Simulation",
        }
    }

    fn description(self) -> &'static str {
        match self {
            Self::Total => {
                "Rumoca = front-end compile + Solve-IR/JIT build + integration; OMC = `timeTotal`."
            }
            Self::Compilation => {
                "Rumoca = front-end compile + Solve-IR/JIT build; OMC = `timeTotal - timeSimulation`."
            }
            Self::Simulation => "Rumoca = `sim_run_seconds`; OMC = `timeSimulation`.",
        }
    }

    fn rumoca_seconds(self, record: &SpeedRecord) -> f64 {
        match self {
            Self::Total => record.rumoca_total(),
            Self::Compilation => record.rumoca_compile(),
            Self::Simulation => record.rumoca_sim_run,
        }
    }

    fn omc_seconds(self, record: &SpeedRecord) -> f64 {
        match self {
            Self::Total => record.omc_total,
            Self::Compilation => record.omc_compile,
            Self::Simulation => record.omc_sim,
        }
    }
}

/// Render speed tables from the full MSL timing artifacts when available. The
/// old `msl_speed_comparison.json` compile-only table is kept as a fallback for
/// partial/local runs that do not upload the joined timing inputs.
fn render_speed_section(results_dir: &Path) -> Result<String> {
    if let Some(records) = collect_detailed_speed_records(results_dir)? {
        if records.is_empty() {
            return Ok("_No agreeing models had valid timings on both tools._\n".to_string());
        }
        return Ok(render_detailed_speed_section(&records));
    }
    render_compile_only_speed_section(results_dir)
}

fn collect_detailed_speed_records(results_dir: &Path) -> Result<Option<Vec<SpeedRecord>>> {
    let msl_path = results_dir.join("msl_results.json");
    let omc_path = results_dir.join("omc_simulation_reference.json");
    let trace_path = results_dir.join("sim_trace_comparison.json");
    if !msl_path.is_file() || !omc_path.is_file() || !trace_path.is_file() {
        return Ok(None);
    }

    let msl = read_json_file(&msl_path)?;
    let omc = read_json_file(&omc_path)?;
    let trace = read_json_file(&trace_path)?;
    let Some(msl_models) = msl.get("model_results").and_then(Value::as_array) else {
        return Ok(None);
    };
    let Some(omc_models) = omc.get("models").and_then(Value::as_object) else {
        return Ok(None);
    };
    let Some(trace_models) = trace.get("models").and_then(Value::as_object) else {
        return Ok(None);
    };

    let rumoca_by_name: BTreeMap<&str, &Value> = msl_models
        .iter()
        .filter_map(|model| Some((json_str(model, "model_name")?, model)))
        .collect();

    let records = trace_models
        .iter()
        .filter(|(_, trace_model)| trace_model_agrees(trace_model))
        .filter_map(|(name, _)| {
            speed_record_from_models(
                name,
                rumoca_by_name.get(name.as_str()).copied()?,
                omc_models.get(name)?,
            )
        })
        .collect();
    Ok(Some(records))
}

fn speed_record_from_models(name: &str, rumoca: &Value, omc: &Value) -> Option<SpeedRecord> {
    if json_str(omc, "status")? != "success" {
        return None;
    }
    let scalar_equations = json_u64(rumoca, "scalar_equations")?;
    let rumoca_frontend_compile = positive_json_f64(rumoca, "compile_seconds")?;
    let rumoca_sim_build = nonnegative_json_f64(rumoca, "sim_build_seconds")?;
    let rumoca_sim_run = positive_json_f64(rumoca, "sim_run_seconds")?;
    let omc_total = positive_json_f64(omc, "total_system_seconds")?;
    let omc_sim = positive_json_f64(omc, "sim_system_seconds")?;
    let omc_compile = omc_total - omc_sim;
    (omc_compile > 0.0).then_some(SpeedRecord {
        model_name: name.to_string(),
        scalar_equations,
        rumoca_frontend_compile,
        rumoca_sim_build,
        rumoca_sim_run,
        omc_compile,
        omc_sim,
        omc_total,
    })
}

fn trace_model_agrees(trace_model: &Value) -> bool {
    let high = json_f64(trace_model, "channel_high_percent").unwrap_or(0.0);
    let near = json_f64(trace_model, "channel_minor_percent").unwrap_or(0.0);
    let deviation = json_f64(trace_model, "channel_deviation_percent").unwrap_or(1.0);
    (high >= 0.80 && deviation <= 0.01) || (high + near >= 0.90 && deviation <= 0.10)
}

fn render_detailed_speed_section(records: &[SpeedRecord]) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "Compilation and simulation are reported separately for the **{} trace-agreeing models** with valid timings on both tools. `Speedup = OMC / Rumoca` (>1 means rumoca faster).\n\n",
        records.len()
    ));
    out.push_str("##### Aggregate speed summary\n\n");
    out.push_str(&render_speed_aggregate_table(records));
    out.push('\n');
    out.push_str("<details>\n<summary><strong>Speed breakdown</strong></summary>\n\n");
    out.push_str("##### Where rumoca's time goes\n\n");
    out.push_str(&render_stage_breakdown_table(records));
    out.push('\n');
    out.push_str(&render_stage_totals_table(records));
    out.push('\n');
    out.push_str("##### Speed by system size\n\n");
    for view in [
        SpeedView::Total,
        SpeedView::Compilation,
        SpeedView::Simulation,
    ] {
        out.push('\n');
        out.push_str(&render_speed_view_table(records, view));
    }
    out.push_str("\n</details>\n");
    out.push('\n');
    out.push_str(&render_slowest_models_tables(records));
    out
}

fn render_speed_aggregate_table(records: &[SpeedRecord]) -> String {
    let mut out = String::from(
        "| Phase | Models | Rumoca total (s) | OMC total (s) | Throughput speedup (×) | Median per-model speedup (×) |\n\
         |---|--:|--:|--:|--:|--:|\n",
    );
    for view in [
        SpeedView::Total,
        SpeedView::Compilation,
        SpeedView::Simulation,
    ] {
        let rumoca_sum = records
            .iter()
            .map(|record| view.rumoca_seconds(record))
            .sum::<f64>();
        let omc_sum = records
            .iter()
            .map(|record| view.omc_seconds(record))
            .sum::<f64>();
        let median_speedup = median_value(
            records
                .iter()
                .map(|record| view.omc_seconds(record) / view.rumoca_seconds(record)),
        );
        out.push_str(&format!(
            "| {} | {} | {rumoca_sum:.1} | {omc_sum:.1} | **{:.2}** | **{median_speedup:.2}** |\n",
            view.label(),
            records.len(),
            omc_sum / rumoca_sum,
        ));
    }
    out
}

fn render_stage_breakdown_table(records: &[SpeedRecord]) -> String {
    let mut out = String::from(
        "| Scalar eqns | Models | front→DAE | Solve-IR + JIT | integration |\n\
         |---|--:|--:|--:|--:|\n",
    );
    for (label, bin_records) in speed_bins(records) {
        out.push_str(&format!(
            "| {label} | {} | {:.3} | {:.3} | {:.4} |\n",
            bin_records.len(),
            median_value(
                bin_records
                    .iter()
                    .map(|record| record.rumoca_frontend_compile)
            ),
            median_value(bin_records.iter().map(|record| record.rumoca_sim_build)),
            median_value(bin_records.iter().map(|record| record.rumoca_sim_run)),
        ));
    }
    out
}

fn render_stage_totals_table(records: &[SpeedRecord]) -> String {
    let frontend = records
        .iter()
        .map(|record| record.rumoca_frontend_compile)
        .sum::<f64>();
    let sim_build = records
        .iter()
        .map(|record| record.rumoca_sim_build)
        .sum::<f64>();
    let sim_run = records
        .iter()
        .map(|record| record.rumoca_sim_run)
        .sum::<f64>();
    let total = frontend + sim_build + sim_run;
    format!(
        "| Rumoca stage | Total seconds | Share of rumoca total |\n\
         |---|--:|--:|\n\
         | front→DAE | {frontend:.1} | {:.0}% |\n\
         | Solve-IR + JIT | {sim_build:.1} | {:.0}% |\n\
         | integration | {sim_run:.1} | {:.0}% |\n",
        stage_share(frontend, total),
        stage_share(sim_build, total),
        stage_share(sim_run, total),
    )
}

fn stage_share(stage_seconds: f64, total_seconds: f64) -> f64 {
    if total_seconds > 0.0 {
        stage_seconds * 100.0 / total_seconds
    } else {
        0.0
    }
}

fn render_speed_view_table(records: &[SpeedRecord], view: SpeedView) -> String {
    let mut out = format!(
        "##### {}\n\n{}\n\n| Scalar eqns | Models | Rumoca (s) | OMC (s) | Speedup (×) |\n|---|--:|--:|--:|--:|\n",
        view.title(),
        view.description()
    );
    for (label, bin_records) in speed_bins(records) {
        let rumoca = median_value(bin_records.iter().map(|record| view.rumoca_seconds(record)));
        let omc = median_value(bin_records.iter().map(|record| view.omc_seconds(record)));
        let speedup = median_value(
            bin_records
                .iter()
                .map(|record| view.omc_seconds(record) / view.rumoca_seconds(record)),
        );
        out.push_str(&format!(
            "| {label} | {} | {rumoca:.4} | {omc:.4} | **{speedup:.2}** |\n",
            bin_records.len()
        ));
    }
    let speedups = records
        .iter()
        .map(|record| view.omc_seconds(record) / view.rumoca_seconds(record))
        .collect::<Vec<_>>();
    out.push_str(&format!(
        "\nPer-model speedup: min {:.2}, median {:.2}, max {:.2}.\n",
        min_value(&speedups),
        median_value(speedups.iter().copied()),
        max_value(&speedups),
    ));
    out
}

fn render_slowest_models_tables(records: &[SpeedRecord]) -> String {
    format!(
        "<details>\n<summary><strong>Top 10 slowest models</strong></summary>\n\n{}\n{}\n</details>\n",
        render_slowest_model_table(records, SpeedView::Compilation),
        render_slowest_model_table(records, SpeedView::Simulation),
    )
}

fn render_slowest_model_table(records: &[SpeedRecord], view: SpeedView) -> String {
    let mut slowest = records.iter().collect::<Vec<_>>();
    slowest.sort_by(|left, right| {
        view.rumoca_seconds(right)
            .total_cmp(&view.rumoca_seconds(left))
    });
    let (title, rumoca_header, omc_header) = match view {
        SpeedView::Compilation => (
            "Top 10 slowest rumoca compilation models",
            "Rumoca compile (s)",
            "OMC compile (s)",
        ),
        SpeedView::Simulation => (
            "Top 10 slowest rumoca simulation models",
            "Rumoca simulation (s)",
            "OMC simulation (s)",
        ),
        SpeedView::Total => (
            "Top 10 slowest rumoca total models",
            "Rumoca total (s)",
            "OMC total (s)",
        ),
    };

    let mut out = format!(
        "##### {title}\n\nTrace-agreeing models ranked by rumoca time.\n\n\
         | Model | Scalar eqns | {rumoca_header} | {omc_header} | Speedup (×) |\n\
         |---|--:|--:|--:|--:|\n"
    );
    for record in slowest.into_iter().take(SLOWEST_MODEL_LIMIT) {
        let rumoca = view.rumoca_seconds(record);
        let omc = view.omc_seconds(record);
        out.push_str(&format!(
            "| `{}` | {} | {rumoca:.4} | {omc:.4} | **{:.2}** |\n",
            record.model_name,
            record.scalar_equations,
            omc / rumoca,
        ));
    }
    out
}

fn speed_bins(records: &[SpeedRecord]) -> Vec<(String, Vec<&SpeedRecord>)> {
    SIZE_BINS
        .iter()
        .filter_map(|(low, high)| {
            let in_bin = records
                .iter()
                .filter(|record| {
                    record.scalar_equations >= *low
                        && high.is_none_or(|high| record.scalar_equations <= high)
                })
                .collect::<Vec<_>>();
            (!in_bin.is_empty()).then(|| (bin_label(*low, *high), in_bin))
        })
        .collect()
}

fn bin_label(low: u64, high: Option<u64>) -> String {
    high.map_or_else(|| format!("{low}+"), |high| format!("{low}–{high}"))
}

fn render_compile_only_speed_section(results_dir: &Path) -> Result<String> {
    let path = results_dir.join("msl_speed_comparison.json");
    if !path.is_file() {
        return Ok("_Report was not produced in this run._\n".to_string());
    }
    let json: Value = serde_json::from_str(
        &fs::read_to_string(&path).with_context(|| format!("failed to read {}", path.display()))?,
    )
    .with_context(|| format!("failed to parse {}", path.display()))?;
    let models = json
        .get("models_compared")
        .and_then(Value::as_u64)
        .unwrap_or(0);
    if models == 0 {
        return Ok(
            "_No models had both an agreeing OMC/rumoca trace and compile timing to compare._\n"
                .to_string(),
        );
    }
    let mut out = String::new();
    if let Some(speedup) = json.get("speedup") {
        let get = |key| speedup.get(key).and_then(Value::as_f64);
        if let (Some(min), Some(median), Some(max)) = (get("min"), get("median"), get("max")) {
            out.push_str(&format!(
                "Over **{models}** models where OMC and rumoca traces agree, rumoca compiled a \
                 **median {median:.1}× faster** than OMC (min {min:.1}×, max {max:.1}×). \
                 `speedup = OMC_compile_s / rumoca_compile_s`; OMC compile = `timeTotal − timeSimulation`.\n\n"
            ));
        }
    }
    out.push_str(
        "| scalar equations | models | rumoca median (s) | OMC median (s) | speedup (×) |\n\
         |---|--:|--:|--:|--:|\n",
    );
    let bins = json
        .get("scaling_by_scalar_equations")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let (mut labels, mut rumoca_line, mut omc_line) = (Vec::new(), Vec::new(), Vec::new());
    for bin in &bins {
        let low = bin.get("bin_low").and_then(Value::as_u64).unwrap_or(0);
        let label = match bin.get("bin_high_inclusive").and_then(Value::as_u64) {
            Some(high) => format!("{low}-{high}"),
            None => format!("{low}+"),
        };
        let count = bin.get("models").and_then(Value::as_u64).unwrap_or(0);
        let median = |group| {
            bin.get(group)
                .and_then(|value| value.get("median"))
                .and_then(Value::as_f64)
                .unwrap_or(0.0)
        };
        let rumoca = median("rumoca_compile_seconds");
        let omc = median("omc_compile_seconds");
        let speedup = bin
            .get("speedup_median")
            .and_then(Value::as_f64)
            .unwrap_or(0.0);
        out.push_str(&format!(
            "| {label} | {count} | {rumoca:.4} | {omc:.4} | {speedup:.2} |\n"
        ));
        labels.push(format!("\"{label}\""));
        rumoca_line.push(format!("{rumoca:.4}"));
        omc_line.push(format!("{omc:.4}"));
    }
    out.push_str(&format!(
        "\nScalability — median compile seconds vs flattened system size (line 1 = rumoca, line 2 = OMC):\n\n\
         ```mermaid\nxychart-beta\n    title \"Compile time vs system size (median s) — line 1 = rumoca, line 2 = OMC\"\n    x-axis [{}]\n    y-axis \"median compile seconds\"\n    line [{}]\n    line [{}]\n```\n",
        labels.join(", "),
        rumoca_line.join(", "),
        omc_line.join(", ")
    ));
    Ok(out)
}

fn read_json_file(path: &Path) -> Result<Value> {
    serde_json::from_str(
        &fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))?,
    )
    .with_context(|| format!("failed to parse {}", path.display()))
}

fn median_value(values: impl IntoIterator<Item = f64>) -> f64 {
    let mut values = values
        .into_iter()
        .filter(|value| value.is_finite())
        .collect::<Vec<_>>();
    if values.is_empty() {
        return 0.0;
    }
    values.sort_by(f64::total_cmp);
    let mid = values.len() / 2;
    if values.len() % 2 == 0 {
        (values[mid - 1] + values[mid]) / 2.0
    } else {
        values[mid]
    }
}

fn min_value(values: &[f64]) -> f64 {
    values.iter().copied().fold(f64::INFINITY, f64::min)
}

fn max_value(values: &[f64]) -> f64 {
    values.iter().copied().fold(f64::NEG_INFINITY, f64::max)
}

fn append_report_section(body: &mut String, title: &str, path: &Path) -> Result<()> {
    if title == "Package Pass Rates" {
        return append_package_pass_rates_section(body, path);
    }

    body.push_str("<details>\n");
    body.push_str(&format!("<summary><strong>{title}</strong></summary>\n\n"));
    if !path.is_file() {
        body.push_str("_Report was not produced in this run._\n\n");
        body.push_str("</details>\n\n");
        return Ok(());
    }
    let text =
        fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))?;
    body.push_str(&report_section_text(title, &text));
    body.push_str("\n\n");
    body.push_str("</details>\n\n");
    Ok(())
}

fn append_package_pass_rates_section(body: &mut String, path: &Path) -> Result<()> {
    body.push_str("#### Package Pass Rates\n\n");
    if !path.is_file() {
        body.push_str("_Report was not produced in this run._\n\n");
        return Ok(());
    }
    let text =
        fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))?;
    body.push_str(&render_package_pass_rates_section(&text));
    body.push_str("\n\n");
    Ok(())
}

fn report_section_text(title: &str, text: &str) -> String {
    let trimmed = text.trim();
    if title == "Package Pass Rates" {
        strip_time_columns(trimmed)
    } else {
        trimmed.to_string()
    }
}

fn render_package_pass_rates_section(text: &str) -> String {
    let table = strip_time_columns(text.trim());
    let lines = table.lines().collect::<Vec<_>>();
    if lines.len() < 3 {
        return table;
    }

    let header = lines[0];
    let separator = lines[1];
    let (overall_rows, package_rows): (Vec<_>, Vec<_>) = lines[2..]
        .iter()
        .partition(|line| markdown_table_cells(line).first() == Some(&"Overall"));
    if overall_rows.is_empty() {
        return table;
    }

    let mut out = String::new();
    out.push_str(header);
    out.push('\n');
    out.push_str(separator);
    out.push('\n');
    for row in overall_rows {
        out.push_str(row);
        out.push('\n');
    }
    if !package_rows.is_empty() {
        out.push_str("\n<details>\n");
        out.push_str("<summary><strong>Per-package pass rates</strong></summary>\n\n");
        out.push_str(header);
        out.push('\n');
        out.push_str(separator);
        out.push('\n');
        for row in package_rows {
            out.push_str(row);
            out.push('\n');
        }
        out.push_str("\n</details>");
    }
    out.trim_end().to_string()
}

fn strip_time_columns(text: &str) -> String {
    let mut out = Vec::new();
    let mut time_indices: Option<Vec<usize>> = None;
    for line in text.lines() {
        if !line.trim_start().starts_with('|') {
            time_indices = None;
            out.push(line.to_string());
            continue;
        }

        let cells = markdown_table_cells(line);
        if time_indices.is_none() {
            let indices = cells
                .iter()
                .enumerate()
                .filter_map(|(index, cell)| (*cell == "Time").then_some(index))
                .collect::<Vec<_>>();
            if !indices.is_empty() {
                time_indices = Some(indices);
            }
        }

        let Some(indices) = time_indices.as_deref() else {
            out.push(line.to_string());
            continue;
        };
        out.push(render_markdown_table_row(&cells, indices));
    }
    out.join("\n")
}

fn markdown_table_cells(line: &str) -> Vec<&str> {
    line.trim()
        .trim_matches('|')
        .split('|')
        .map(str::trim)
        .collect()
}

fn render_markdown_table_row(cells: &[&str], remove_indices: &[usize]) -> String {
    let kept = cells
        .iter()
        .enumerate()
        .filter_map(|(index, cell)| (!remove_indices.contains(&index)).then_some(*cell))
        .collect::<Vec<_>>();
    format!("| {} |", kept.join(" | "))
}

fn append_optional_link_note(body: &mut String, results_dir: &Path) {
    let compatibility = results_dir.join("msl_compatibility_report.md");
    let modelica_test = results_dir.join("modelica_test_catalog.md");
    if !compatibility.is_file() && !modelica_test.is_file() {
        return;
    }

    body.push_str("#### Additional Artifacts\n\n");
    if compatibility.is_file() {
        body.push_str("- `msl_compatibility_report.md`\n");
    }
    if modelica_test.is_file() {
        body.push_str("- `modelica_test_catalog.md`\n");
    }
    body.push('\n');
}

fn json_str<'a>(json: &'a Value, key: &str) -> Option<&'a str> {
    json.get(key).and_then(Value::as_str)
}

fn json_u64(json: &Value, key: &str) -> Option<u64> {
    json.get(key).and_then(Value::as_u64)
}

fn json_f64(json: &Value, key: &str) -> Option<f64> {
    json.get(key).and_then(Value::as_f64)
}

fn positive_json_f64(json: &Value, key: &str) -> Option<f64> {
    let value = json_f64(json, key)?;
    (value.is_finite() && value > 0.0).then_some(value)
}

fn nonnegative_json_f64(json: &Value, key: &str) -> Option<f64> {
    let value = json_f64(json, key)?;
    (value.is_finite() && value >= 0.0).then_some(value)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pr_comment_renders_existing_msl_reports() {
        let temp = tempfile::tempdir().expect("tempdir");
        let results = temp.path();
        let baseline_path = write_existing_msl_report_inputs(results);

        let rendered = render_pr_comment(results, Some(&baseline_path)).expect("render comment");
        assert!(rendered.contains(COMMENT_MARKER));
        assert!(rendered.contains(
            "| `full` | `v4.1.0` | `OpenModelica 1.26.1` | 10/10 (Δ+2/0) | 9/10 (Δ+1/0) | 8/10 (Δ0/0) | 7/10 (Δ+2/0) |"
        ));
        assert!(rendered.contains("Deltas compare numerator/denominator"));
        assert!(rendered.contains(
            "Baseline: quality gate v1, commit `bac3be3`, MSL `v4.1.0`, OMC `OpenModelica 1.26.7`"
        ));
        assert!(rendered.contains("#### CI Gate Snapshot"));
        assert!(rendered.contains(
            "| Structural floors | parse 10 (0), flat 9 (+1), DAE 10 (+2), solve 7 (+1) |"
        ));
        assert!(rendered.contains(
            "| Trace floors | acceptable 6/10 (+2), no-severe 6/10 (+2), compared 7 (+1) |"
        ));
        assert!(rendered.contains("<summary><strong>CI gate details</strong></summary>"));
        assert!(rendered.contains("| Flatten floor | 9/10 | 8/10 | +1 |"));
        assert!(rendered.contains("| Solve-IR floor | 7/10 | 6/10 | +1 |"));
        assert!(rendered.contains("IC progress is contextual unless simulation successes regress"));
        assert!(rendered.contains("| IC progress | 6/10 | 5/10 | +1 |"));
        assert!(rendered.contains("| Trace acceptable floor | 6/10 | 4/10 | +2 |"));
        assert!(rendered.contains("| Trace no-severe floor | 6/10 | 4/10 | +2 |"));
        assert!(rendered.contains("| Trace compared floor (drop ≤2) | 7 | 6 | +1 |"));
        assert!(rendered.contains("Trace agreement vs baseline: high+near Δ+2, deviation Δ-1"));
        assert!(rendered.contains("#### Package Pass Rates"));
        assert!(rendered.contains("| MSL Package | n | Ast | Flat |"));
        assert!(rendered.contains("| Overall | 10 | 100% | 90% |"));
        assert!(rendered.contains("<summary><strong>Per-package pass rates</strong></summary>"));
        assert!(rendered.contains("| Blocks | 10 | 100% | 90% |"));
        assert!(!rendered.contains("0.01s"));
        assert!(rendered.contains("<summary><strong>MLS Contract Coverage</strong></summary>"));
        assert!(rendered.contains("| OTHER | 10 |"));
    }

    fn write_existing_msl_report_inputs(results: &Path) -> PathBuf {
        write_existing_quality_snapshot(results);
        let baseline_path = results.join("msl_quality_baseline.json");
        write_existing_quality_baseline(&baseline_path);
        write_existing_markdown_reports(results);
        baseline_path
    }

    fn write_existing_quality_snapshot(results: &Path) {
        fs::write(
            results.join("msl_quality_current.json"),
            r#"{
                "run_scope": "full",
                "msl_version": "v4.1.0",
                "omc_version": "OpenModelica 1.26.1",
                "simulatable_attempted": 10,
                "parse_models": 10,
                "flatten_models": 9,
                "solve_models": 7,
                "compiled_models": 10,
                "balance_denominator": 10,
                "balanced_models": 9,
                "partial_models": 1,
                "unbalanced_models": 0,
                "initial_balanced_models": 8,
                "sim_target_models": 10,
                "ic_ok": 6,
                "sim_ok": 7,
                "sim_attempted": 10,
                "trace_accuracy_stats": {
                    "models_compared": 7,
                    "agreement_high": 4,
                    "agreement_minor": 2,
                    "agreement_deviation": 1,
                    "models_with_severe_channel": 1
                }
            }"#,
        )
        .expect("write quality snapshot");
    }

    fn write_existing_quality_baseline(baseline_path: &Path) {
        fs::write(
            baseline_path,
            r#"{
                "quality_gate_version": 1,
                "git_commit": "bac3be350bc0eecb0727f3f0fa27c38320b81173",
                "msl_version": "v4.1.0",
                "omc_version": "OpenModelica 1.26.7",
                "simulatable_attempted": 10,
                "parse_models": 10,
                "flatten_models": 8,
                "solve_models": 6,
                "compiled_models": 8,
                "balance_denominator": 10,
                "balanced_models": 8,
                "partial_models": 1,
                "unbalanced_models": 0,
                "initial_balanced_models": 8,
                "sim_target_models": 10,
                "ic_ok": 5,
                "sim_ok": 5,
                "sim_attempted": 9,
                "trace_accuracy_stats": {
                    "models_compared": 6,
                    "agreement_high": 3,
                    "agreement_minor": 1,
                    "agreement_deviation": 2,
                    "models_with_severe_channel": 2
                }
            }"#,
        )
        .expect("write quality baseline");
    }

    fn write_existing_markdown_reports(results: &Path) {
        fs::write(
            results.join("mls_contract_coverage.md"),
            "| MLS Category | n |\n|---|---:|\n| OTHER | 10 |\n",
        )
        .expect("write coverage");
        fs::write(
            results.join("msl_package_pass_rates.md"),
            "| MSL Package | n | Ast | Time | Flat | Time |\n\
             |---|---:|---:|---:|---:|---:|\n\
             | Blocks | 10 | 100% | 0.01s | 90% | 0.02s |\n\
             | Overall | 10 | 100% | 0.01s | 90% | 0.02s |\n",
        )
        .expect("write pass rates");
        fs::write(
            results.join("msl_package_trace_accuracy.md"),
            "| MSL Package | Trace |\n|---|---:|\n| Blocks | 90% |\n",
        )
        .expect("write trace accuracy");
    }

    #[test]
    fn pr_comment_renders_detailed_speed_tables() {
        let temp = tempfile::tempdir().expect("tempdir");
        let results = temp.path();
        fs::write(
            results.join("msl_results.json"),
            r#"{
                "model_results": [
                    {
                        "model_name": "Modelica.Blocks.Examples.A",
                        "scalar_equations": 5,
                        "compile_seconds": 1.0,
                        "sim_build_seconds": 0.5,
                        "sim_run_seconds": 0.5
                    },
                    {
                        "model_name": "Modelica.Blocks.Examples.B",
                        "scalar_equations": 12,
                        "compile_seconds": 2.0,
                        "sim_build_seconds": 1.0,
                        "sim_run_seconds": 1.0
                    }
                ]
            }"#,
        )
        .expect("write msl results");
        fs::write(
            results.join("omc_simulation_reference.json"),
            r#"{
                "models": {
                    "Modelica.Blocks.Examples.A": {
                        "status": "success",
                        "total_system_seconds": 5.0,
                        "sim_system_seconds": 1.0
                    },
                    "Modelica.Blocks.Examples.B": {
                        "status": "success",
                        "total_system_seconds": 8.0,
                        "sim_system_seconds": 2.0
                    }
                }
            }"#,
        )
        .expect("write omc reference");
        fs::write(
            results.join("sim_trace_comparison.json"),
            r#"{
                "models": {
                    "Modelica.Blocks.Examples.A": {
                        "channel_high_percent": 1.0,
                        "channel_minor_percent": 0.0,
                        "channel_deviation_percent": 0.0
                    },
                    "Modelica.Blocks.Examples.B": {
                        "channel_high_percent": 0.8,
                        "channel_minor_percent": 0.1,
                        "channel_deviation_percent": 0.1
                    }
                }
            }"#,
        )
        .expect("write trace comparison");

        let rendered = render_speed_section(results).expect("render speed section");

        assert!(rendered.contains("Aggregate speed summary"));
        assert!(rendered.contains("| Total | 2 | 6.0 | 13.0 | **2.17** | **2.25** |"));
        assert!(rendered.contains("Where rumoca's time goes"));
        assert!(rendered.contains("<summary><strong>Speed breakdown</strong></summary>"));
        assert!(rendered.contains("Table 1 — Total"));
        assert!(rendered.contains("Table 2 — Compilation"));
        assert!(rendered.contains("Table 3 — Simulation"));
        assert!(rendered.contains("| 1–9 | 1 | 2.0000 | 5.0000 | **2.50** |"));
        assert!(!rendered.contains("All (sum)"));
        assert!(rendered.contains("<summary><strong>Top 10 slowest models</strong></summary>"));
        assert!(rendered.contains("Top 10 slowest rumoca compilation models"));
        assert!(rendered.contains("Top 10 slowest rumoca simulation models"));
        assert!(
            rendered.contains("| `Modelica.Blocks.Examples.B` | 12 | 3.0000 | 6.0000 | **2.00** |")
        );
        assert!(
            rendered.contains("| `Modelica.Blocks.Examples.B` | 12 | 1.0000 | 2.0000 | **2.00** |")
        );
    }

    #[test]
    fn pr_comment_marks_missing_reports_without_failing() {
        let temp = tempfile::tempdir().expect("tempdir");
        let rendered = render_pr_comment(
            temp.path(),
            Some(&temp.path().join("missing-baseline.json")),
        )
        .expect("render missing-report comment");
        assert!(rendered.contains(COMMENT_MARKER));
        assert!(rendered.contains("_Report was not produced in this run._"));
    }

    #[test]
    fn pr_comment_keeps_summary_without_missing_baseline() {
        let temp = tempfile::tempdir().expect("tempdir");
        let results = temp.path();
        fs::write(
            results.join("msl_quality_current.json"),
            r#"{
                "run_scope": "full",
                "msl_version": "v4.1.0",
                "omc_version": "OpenModelica 1.26.1",
                "compiled_models": 10,
                "balance_denominator": 10,
                "balanced_models": 9,
                "initial_balanced_models": 8,
                "sim_target_models": 10,
                "sim_ok": 7,
                "sim_attempted": 8
            }"#,
        )
        .expect("write quality snapshot");

        let rendered = render_pr_comment(results, Some(&results.join("missing-baseline.json")))
            .expect("render comment");
        assert!(rendered.contains(
            "| `full` | `v4.1.0` | `OpenModelica 1.26.1` | 10/10 | 9/10 | 8/10 | 7/10 |"
        ));
        assert!(!rendered.contains("Deltas compare numerator/denominator"));
    }

    #[test]
    fn pr_comment_simulation_summary_uses_ci_gate_denominator() {
        let temp = tempfile::tempdir().expect("tempdir");
        let results = temp.path();
        fs::write(
            results.join("msl_quality_current.json"),
            r#"{
                "run_scope": "full",
                "msl_version": "v4.1.0",
                "omc_version": "OpenModelica 1.26.1",
                "compiled_models": 10,
                "balance_denominator": 10,
                "balanced_models": 9,
                "initial_balanced_models": 8,
                "sim_target_models": 10,
                "sim_ok": 0,
                "sim_attempted": 0
            }"#,
        )
        .expect("write quality snapshot");

        let rendered = render_pr_comment(results, None).expect("render comment");

        assert!(rendered.contains(
            "| `full` | `v4.1.0` | `OpenModelica 1.26.1` | 10/10 | 9/10 | 8/10 | 0/10 |"
        ));
        assert!(!rendered.contains("| 10/10 | 9/10 | 8/10 | 0/0 |"));
    }
}
