version = 1

[libraries.msl]
display_name = "MSL"
version = "4.1.0"
url = "https://github.com/modelica/ModelicaStandardLibrary/releases/download/v4.1.0/ModelicaStandardLibrary_v4.1.0.zip"
sha256 = "5409cfa17797c52d866dc9d2675badc1378b4bbf88066e60899a489cb1cb8a2d"
cache_dir = "target/msl/ModelicaStandardLibrary-4.1.0"
zip_layout = "direct"
required_files = [
  "Complex.mo",
  "Modelica 4.1.0/package.mo",
]

[libraries.cmm]
display_name = "CMM"
version = "main-a642c381"
url = "https://github.com/CogniPilot/modelica_models/archive/a642c381a551afd247e784648f0aedb16d0c027c.zip"
sha256 = "ca47391811532c89300e52bb8ce53ee4bfd6d6d8412d54e2f13f11387f44dcc3"
cache_dir = "target/cmm/CMM-a642c381"
zip_layout = "auto-strip-common-root"
required_files = [
  "LieGroups/package.mo",
  "RigidBody/package.mo",
]
write_revision_marker = true
