//! Embeds the vendored eFMI Beta-1 XSD tree (`assets/efmi-schemas/`) into the
//! crate as a generated static, so every emitted eFMU `schemas/` directory is
//! populated byte-identically from the vendored assets (GAL-023) without any
//! runtime dependency on the source checkout.
//!
//! The generated file (`$OUT_DIR/schema_assets.rs`) defines the
//! `SCHEMA_ASSETS` static consumed by `src/container.rs`. Entries are sorted
//! by relative path for deterministic output. The top-level `README.md` is
//! excluded: it is repository documentation about the vendoring, not part of
//! the eFMI schema distribution; everything else — all XSDs, `VERSION.txt`
//! files, and the BSD-3-Clause `LICENSE` — is embedded verbatim.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// Repository-only files at the asset-tree root that must not be copied into
/// emitted `schemas/` directories.
const EXCLUDED_ROOT_FILES: &[&str] = &["README.md"];

fn main() -> Result<(), String> {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set"));
    let assets_dir = manifest_dir.join("assets").join("efmi-schemas");
    println!("cargo:rerun-if-changed={}", assets_dir.display());

    let mut relative_paths = Vec::new();
    collect_files(&assets_dir, &assets_dir, &mut relative_paths)?;
    relative_paths.sort();

    let generated = render_manifest(&assets_dir, &relative_paths);
    let out_path =
        PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is set")).join("schema_assets.rs");
    fs::write(&out_path, generated).map_err(|error| {
        format!(
            "write generated schema asset manifest {}: {error}",
            out_path.display()
        )
    })?;
    Ok(())
}

/// Recursively collect files under `dir` as `/`-separated paths relative to
/// `root`, skipping the excluded root-level repository files. I/O failures
/// are reported with the offending directory path so the build error points
/// at the vendored asset tree.
fn collect_files(root: &Path, dir: &Path, out: &mut Vec<String>) -> Result<(), String> {
    let entries = fs::read_dir(dir)
        .map_err(|error| format!("read vendored asset dir {}: {error}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|error| {
            format!(
                "read vendored asset dir entry in {}: {error}",
                dir.display()
            )
        })?;
        let path = entry.path();
        if path.is_dir() {
            collect_files(root, &path, out)?;
            continue;
        }
        let relative = path
            .strip_prefix(root)
            .expect("asset path is under the asset root")
            .components()
            .map(|c| c.as_os_str().to_str().expect("asset paths are UTF-8"))
            .collect::<Vec<_>>()
            .join("/");
        if dir == root && EXCLUDED_ROOT_FILES.contains(&relative.as_str()) {
            continue;
        }
        out.push(relative);
    }
    Ok(())
}

/// Render the `SCHEMA_ASSETS` static; the `SchemaAsset` type is defined by
/// the including module (`src/container.rs`).
fn render_manifest(assets_dir: &Path, relative_paths: &[String]) -> String {
    let mut code = String::new();
    code.push_str(
        "/// Vendored eFMI Beta-1 schema tree (generated by build.rs; GAL-023).\n\
         static SCHEMA_ASSETS: &[SchemaAsset] = &[\n",
    );
    for relative in relative_paths {
        let absolute = assets_dir.join(relative.replace('/', std::path::MAIN_SEPARATOR_STR));
        writeln!(
            code,
            "    SchemaAsset {{ relative_path: {relative:?}, bytes: include_bytes!({:?}) }},",
            absolute.display().to_string()
        )
        .expect("writing to a String cannot fail");
    }
    code.push_str("];\n");
    code
}
