# Generated by Rumoca - CasADi MX Code
#
# This file was automatically generated from a Modelica model.
# Do not edit manually.
#
# MX mode: variables are vector symbols with named slices.
# Functions and the DAE itself are casadi.Function objects,
# enabling differentiation, serialization, and composition.

import casadi as ca
import numpy as np

def _size(x, dim=None):
    """Modelica size() for CasADi MX objects, Python lists, and numpy arrays."""
    if dim is None:
        return len(x) if hasattr(x, '__len__') else x.size1()
    if dim == 1:
        return len(x) if hasattr(x, '__len__') else x.size1()
    return x.shape[dim - 1] if hasattr(x, 'shape') else x.size2()

def _sum(x):
    """Modelica sum() for CasADi: handles lists, comprehensions, and MX vectors."""
    if isinstance(x, list):
        return ca.sum1(ca.vertcat(*x))
    return ca.sum1(x)

def pre(x):
    """Modelica pre() operator for CasADi.

    During continuous integration, pre(x) = x since events are not handled
    mid-step. A full event-driven simulation driver would snapshot discrete
    variables at event boundaries and substitute them here.
    """
    return x

def Clock(*args):
    """Modelica Clock() constructor stub (MLS §16.3).

    In continuous CasADi simulation, clocked constructs are not meaningful.
    Returns 0 so that expressions referencing Clock() do not crash.
    """
    return 0

def previous(x):
    """Modelica previous() operator stub (MLS §16.4).

    In continuous simulation, previous(x) = x (no discrete tick tracking).
    """
    return x

def firstTick(*args):
    """Modelica firstTick() operator stub (MLS §16.10).

    Returns False — not at a first tick in continuous simulation.
    """
    return False

def interval(*args):
    """Modelica interval() operator stub (MLS §16.10).

    Returns 0.0 — clock interval is not meaningful in continuous simulation.
    """
    return 0.0

def hold(x):
    """Modelica hold() operator stub (MLS §16.5.1).

    In continuous simulation, pass through the value unchanged.
    """
    return x

def subSample(x, *args):
    """Modelica subSample() operator stub (MLS §16.5.2). Pass through."""
    return x

def superSample(x, *args):
    """Modelica superSample() operator stub (MLS §16.5.2). Pass through."""
    return x

def shiftSample(x, *args):
    """Modelica shiftSample() operator stub (MLS §16.5.3). Pass through."""
    return x

def backSample(x, *args):
    """Modelica backSample() operator stub (MLS §16.5.3). Pass through."""
    return x

def noClock(x):
    """Modelica noClock() operator stub (MLS §16.5.4). Pass through."""
    return x

def Complex(re, im=0):
    """Complex record constructor — projects to real part for real-valued DAE."""
    return re

def Modelica_ComplexMath_abs(c_re, c_im=0):
    """ComplexMath.abs: magnitude of complex number (uses real sqrt)."""
    return ca.sqrt(ca.power(c_re, 2) + ca.power(c_im, 2))

def Modelica_ComplexMath_sqrt(c1_re, c1_im=0):
    """ComplexMath.sqrt: square root of complex number."""
    r = Modelica_ComplexMath_abs(c1_re, c1_im)
    phi = ca.atan2(c1_im, c1_re)
    return ca.sqrt(r) * ca.cos(phi / 2.0)

def Modelica_ComplexMath_arg(c_re, c_im=0):
    """ComplexMath.arg: argument (phase angle) of complex number."""
    return ca.atan2(c_im, c_re)




def create_model():
    """Create CasADi MX model with vector symbols and Function objects.

    Returns:
        dict: Model dictionary with casadi.Function DAE and metadata.
    """

    # Time symbol
    t = ca.MX.sym('t')
    time = t  # Modelica built-in `time` maps to CasADi time symbol

    # =========================================================================
    # State Variables (2 variables)
    # =========================================================================
    n_x = 2
    _x = ca.MX.sym('x', n_x)
    _xdot = ca.MX.sym('xdot', n_x)

    # Named slices into _x (0-indexed)
    x = _x[0]  # x
    v = _x[1]  # v

    # der() maps state variables to _xdot slices via CasADi symbolic comparison
    _der_pairs = [
        (x, _xdot[0]),
        (v, _xdot[1]),
    ]
    def der(v):
        for _state, _deriv in _der_pairs:
            if _state.shape == v.shape and ca.is_equal(v, _state):
                return _deriv
        raise ValueError(f"der() called on non-state variable: {v}")

    # =========================================================================
    # Continuous Algebraic Variables (0 algebraics + 0 outputs)
    # =========================================================================
    n_z = 0
    n_z_continuous = 0
    n_z_discrete = 0
    _z_c = ca.MX.sym('z_c', 0)
    _z_d = ca.MX.sym('z_d', 0)
    _z = ca.vertcat(_z_c, _z_d)

    # =========================================================================
    # Input Variables (0 variables)
    # =========================================================================
    n_u = 0
    _u = ca.MX.sym('u', 0)

    # =========================================================================
    # Parameters (2 variables)
    # =========================================================================
    n_p = 2
    _p = ca.MX.sym('p', n_p)

    # Named slices into _p
    k = _p[0]  # k
    m = _p[1]  # m

    # =========================================================================
    # Constants
    # =========================================================================


    # Enumeration literal ordinals (MLS §4.9.5)
    StateSelect_never = 1
    StateSelect_avoid = 2
    StateSelect_default = 3
    StateSelect_prefer = 4
    StateSelect_always = 5
    AssertionLevel_warning = 1
    AssertionLevel_error = 2

    # =========================================================================
    # User-Defined Functions (0)
    # =========================================================================
    # =========================================================================
    # Continuous Implicit Equations f_x (2)
    # =========================================================================
    f_x = ca.vertcat(
        (der(x) - v),  # equation from 
        ((m * der(v)) - (-(k * x)))  # equation from 
    )

    # =========================================================================
    # DAE as CasADi Function
    # =========================================================================
    # _z is vertcat(_z_c, _z_d) which is not a pure symbol, so we create a
    # fresh monolithic symbol for the Function interface and substitute.
    _z_sym = ca.MX.sym('z', n_z)
    _f_x_for_fn = ca.substitute(
        [f_x],
        [_z_c, _z_d],
        [_z_sym[:n_z_continuous], _z_sym[n_z_continuous:]]
    )[0]
    dae_fn = ca.Function('dae',
        [_x, _xdot, _z_sym, _u, _p, t],
        [_f_x_for_fn],
        ['x', 'xdot', 'z', 'u', 'p', 't'],
        ['f_x'])

    # =========================================================================
    # Integrator Builder
    # =========================================================================
    def build_integrator(dt, opts=None, method='idas'):
        """Build a CasADi integrator from the implicit DAE residual.

        For pure ODEs (no algebraics, exactly n_x equations), converts to
        explicit form via mass-matrix inversion and uses CVODES.

        For DAE systems or over-determined ODEs, uses an augmented-z
        approach: xdot symbols are included in the algebraic vector so the
        chosen DAE solver receives the original residual directly.

        Args:
            dt: Time grid (scalar step or array of output times).
            opts: Optional dict of integrator options passed to ca.integrator().
            method: DAE solver — 'idas' (default) or 'collocation'.
                IDAS is faster but requires consistent initial conditions.
                Collocation handles structurally singular DAEs where
                IDACalcIC fails.

        Returns:
            A CasADi integrator Function.
        """
        # Discrete variables are treated as fixed parameters during continuous
        # integration (MLS §8.5). Only continuous algebraics (y, w) are part of
        # the DAE solved by IDAS. Discrete variables (z, m) are updated at
        # event boundaries by the simulation driver.
        # _z_c and _z_d are already pure MX symbols (declared at module level).
        if n_z_discrete > 0:
            _p_full = ca.vertcat(_p, _u, _z_d)
        else:
            _p_full = ca.vertcat(_p, _u)
        _n_eq = f_x.shape[0]

        # Pure ODE: exactly n_x equations, no continuous algebraics → explicit CVODES
        if _n_eq == n_x and n_z_continuous == 0:
            _M = ca.jacobian(f_x, _xdot)
            _f0 = ca.substitute(f_x, _xdot, ca.MX.zeros(n_x))
            _ode = ca.solve(_M, -_f0)
            _dae = {'x': _x, 't': t, 'ode': _ode, 'p': _p_full}
            return ca.integrator('integrator', 'cvodes', _dae, 0, dt, opts or {})

        # General DAE / over-determined ODE: augmented-z approach.
        # Include xdot in the algebraic vector so IDAS solves the original
        # implicit residual f_x(x, xdot, z_c, p, t) = 0 directly.
        # Only continuous algebraics are in the augmented z vector.
        # CasADi requires purely symbolic integrator inputs, so we create a
        # fresh symbol and substitute the original xdot/_z_c references.
        _n_z_aug = n_x + n_z_continuous
        _z_aug = ca.MX.sym('z_aug', _n_z_aug)
        _xdot_aug = _z_aug[:n_x]
        _z_c_aug = _z_aug[n_x:]
        _f_x_sub = ca.substitute([f_x], [_xdot, _z_c], [_xdot_aug, _z_c_aug])[0]
        _dae = {
            'x': _x, 'z': _z_aug, 't': t,
            'ode': _xdot_aug,
            'alg': _f_x_sub,
            'p': _p_full,
        }
        return ca.integrator('integrator', method, _dae, 0, dt, opts or {})

    # =========================================================================
    # Default Values
    # =========================================================================
    def _flat_start(value, expected_size, var_name):
        # Convert value to a float64 numpy array.  When `value` is a CasADi
        # symbolic expression (e.g. a parameter whose start references another
        # parameter), np.array(..., dtype=float64) will fail; fall back to
        # float() which works on constant CasADi expressions.
        if isinstance(value, (bool, np.bool_)):
            value = float(value)
        try:
            arr = np.array(value, dtype=np.float64).reshape(-1)
        except (ValueError, TypeError, RuntimeError):
            try:
                arr = np.array([float(value)], dtype=np.float64)
            except (ValueError, TypeError, RuntimeError):
                arr = np.zeros(expected_size, dtype=np.float64)
        if arr.size == expected_size:
            return arr
        if arr.size == 1 and expected_size > 1:
            return np.repeat(arr, expected_size)
        raise ValueError(
            f"Start value size mismatch for {var_name}: expected {expected_size}, got {arr.size}"
        )

    _x0_parts = []
    _x0_parts.append(_flat_start(
        1.0,
        1,
        'x'
    ))
    _x0_parts.append(_flat_start(
        0.0,
        1,
        'v'
    ))
    x0 = np.concatenate(_x0_parts) if _x0_parts else np.array([])

    _p0_parts = []
    _p0_parts.append(_flat_start(
        1.0,
        1,
        'k'
    ))
    _p0_parts.append(_flat_start(
        1.0,
        1,
        'm'
    ))
    p0 = np.concatenate(_p0_parts) if _p0_parts else np.array([])

    # Algebraic initial guesses (continuous y, w then discrete z, m)
    _z0_parts = []
    z0 = np.concatenate(_z0_parts) if _z0_parts else np.array([])

    return {
        'name': 'Model',
        't': t,
        'x': _x,
        'xdot': _xdot,
        'z': _z,
        'u': _u,
        'p': _p,
        'f_x': f_x,
        'dae_fn': dae_fn,
        'build_integrator': build_integrator,
        'x0': x0,
        'p0': p0,
        'z0': z0,
        'n_x': n_x,
        'n_z': n_z,
        'n_z_continuous': n_z_continuous,
        'n_u': n_u,
        'n_p': n_p,
        'state_names': ['x', 'v'],
        'algebraic_names': [],
        'input_names': [],
        'param_names': ['k', 'm'],
    }


# =========================================================================
# Convenience Functions
# =========================================================================

def get_state_names():
    """Get list of state variable names."""
    return ['x', 'v']


def get_param_names():
    """Get list of parameter names."""
    return ['k', 'm']


def get_input_names():
    """Get list of input variable names."""
    return []


def simulate(x0=None, p0=None, u0=None, t_span=(0.0, 1.0), dt=0.01):
    """Simulate the model using CasADi integrator.

    Args:
        x0: Initial state (numpy array). Uses model defaults if None.
        p0: Parameters (numpy array). Uses model defaults if None.
        u0: Inputs (numpy array). Uses zeros if None.
        t_span: Tuple of (t0, tf) time span.
        dt: Integration time step.

    Returns:
        Tuple of (times, states) where times is a 1-D array of length
        n_steps+1 and states is an (n_x, n_steps+1) numpy array.
    """
    model = create_model()
    if x0 is None:
        x0 = model['x0']
    if p0 is None:
        p0 = model['p0']
    if u0 is None:
        u0 = np.zeros(model['n_u'])

    t0, tf = t_span
    tgrid = np.arange(t0, tf + dt * 0.5, dt)
    integrator = model['build_integrator'](tgrid)
    p_full = np.concatenate([p0, u0])
    result = integrator(x0=x0, p=p_full)
    states = np.array(result['xf'])
    return tgrid, states


def simulate_csv(t_end=1.0, dt=0.01):
    """Run simulation and return CSV string.

    Args:
        t_end: End time (start is always 0).
        dt: Integration time step.

    Returns:
        CSV string with header row and one row per time step.
    """
    ts, xs = simulate(t_span=(0.0, t_end), dt=dt)
    names = get_state_names()
    header = "time," + ",".join(names)
    rows = [header]
    for j in range(len(ts)):
        row = [f"{float(ts[j]):.10g}"]
        for i in range(xs.shape[0]):
            row.append(f"{float(xs[i, j]):.10g}")
        rows.append(",".join(row))
    return "\n".join(rows)


if __name__ == '__main__':
    model = create_model()
    print(f"States ({model['n_x']}): {model['state_names']}")
    print(f"Algebraics ({model['n_z']}): {model['algebraic_names']}")
    print(f"Parameters ({model['n_p']}): {model['param_names']}")

    # Test the DAE function
    dae_fn = model['dae_fn']
    print(f"\nDAE Function: {dae_fn}")
    print(f"  Inputs: {dae_fn.name_in()}")
    print(f"  Outputs: {dae_fn.name_out()}")

    # Verify differentiability
    if model['n_x'] > 0:
        J = dae_fn.jacobian()
        print(f"\nJacobian computable: {J}")

    # Quick simulation demo
    if model['n_x'] > 0:
        ts, xs = simulate()
        print(f"\nSimulated {len(ts)} steps, final state: {xs[:, -1]}")